# Generated by Django 2.0.3 on 2018-06-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180611_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='./ArticleImage/'),
        ),
    ]
