# Generated by Django 2.0.4 on 2018-06-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20180622_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
